In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [78]:
df = pd.read_csv(r'C:\Users\Joan Oliver\TheBridge-DataScienceBootcamp\data-science-pt-2023-01\Machine_Learning\Kaggle_2\train.csv')

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73363 entries, 0 to 73362
Data columns (total 12 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Id                                    73363 non-null  int64  
 1   target                                73363 non-null  int64  
 2   RevolvingUtilizationOfUnsecuredLines  73363 non-null  float64
 3   age                                   73363 non-null  object 
 4   NumberOfTime30-59DaysPastDueNotWorse  73363 non-null  int64  
 5   DebtRatio                             73363 non-null  float64
 6   MonthlyIncome                         58796 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       73363 non-null  int64  
 8   NumberOfTimes90DaysLate               73363 non-null  int64  
 9   NumberRealEstateLoansOrLines          73363 non-null  int64  
 10  NumberOfTime60-89DaysPastDueNotWorse  73363 non-null  int64  
 11  NumberOfDepende

In [80]:
df.set_index('Id', inplace=True)

## Limpieza de datos

In [81]:
df["age"] = df["age"].str.replace("y", "").astype(int)

In [82]:
df["age"] = df["age"].replace(0, 18).astype(int)

In [95]:
df["MonthlyIncome"] = df["MonthlyIncome"].fillna(df["MonthlyIncome"].median())

In [96]:
df["NumberOfDependents"] = df["NumberOfDependents"].fillna(0)

In [97]:
df.describe().T

count         mean          std   min  \
target                                73363.0     0.065919     0.248142   0.0   
RevolvingUtilizationOfUnsecuredLines  73363.0     5.884904   235.508449   0.0   
age                                   73363.0    52.363153    14.780370  18.0   
NumberOfTime30-59DaysPastDueNotWorse  73363.0     0.410507     4.090014   0.0   
DebtRatio                             73363.0   359.752537  2477.648064   0.0   
MonthlyIncome                         73363.0  6401.113777  9378.812902   0.0   
NumberOfOpenCreditLinesAndLoans       73363.0     8.443916     5.142232   0.0   
NumberOfTimes90DaysLate               73363.0     0.256546     4.066573   0.0   
NumberRealEstateLoansOrLines          73363.0     1.019928     1.136357   0.0   
NumberOfTime60-89DaysPastDueNotWorse  73363.0     0.231847     4.052280   0.0   
NumberOfDependents                    73363.0     0.735507     1.103586   0.0   

                                              25%          50%          75%  \
target                                   0.000000     0.000000     0.000000   
RevolvingUtilizationOfUnsecuredLines     0.029752     0.154688     0.558686   
age                                     41.000000    52.000000    63.000000   
NumberOfTime30-59DaysPastDueNotWorse     0.000000     0.000000     0.000000   
DebtRatio                                0.173446     0.365737     0.863514   
MonthlyIncome                         3900.000000  5400.000000  7401.500000   
NumberOfOpenCreditLinesAndLoans          5.000000     8.000000    11.000000   
NumberOfTimes90DaysLate                  0.000000     0.000000     0.000000   
NumberRealEstateLoansOrLines             0.000000     1.000000     2.000000   
NumberOfTime60-89DaysPastDueNotWorse     0.000000     0.000000     0.000000   
NumberOfDependents                       0.000000     0.000000     1.000000   

                                            max  
target                                      1.0  
RevolvingUtilizationOfUnsecuredLines    29110.0  
age                                       105.0  
NumberOfTime30-59DaysPastDueNotWorse       98.0  
DebtRatio                              329664.0  
MonthlyIncome                         1560100.0  
NumberOfOpenCreditLinesAndLoans            57.0  
NumberOfTimes90DaysLate                    98.0  
NumberRealEstateLoansOrLines               32.0  
NumberOfTime60-89DaysPastDueNotWorse       98.0  
NumberOfDependents                         13.0

In [98]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.20, random_state=42)

## Logistic Regression

In [99]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)

c:\Users\Joan Oliver\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [101]:
kfold = model_selection.KFold(n_splits=10)
cv_results = model_selection.cross_val_score(logistic_model, X_train, y_train, cv=kfold)
msg = "Accuracy: %.2f%% (%.2f%%)" % (cv_results.mean()*100, cv_results.std()*100)
print(cv_results)
print(msg)

c:\Users\Joan Oliver\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
c:\Users\Joan Oliver\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    

[0.93985347 0.93133413 0.93014142 0.93337877 0.93695689 0.93184529
 0.93354916 0.9316749  0.93133413 0.93610496]
Accuracy: 93.36% (0.29%)


c:\Users\Joan Oliver\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [159]:
logistic_model.coef_[0]

array([-5.88980281e-03, -4.94750514e-02,  2.79837171e-01, -3.18762474e-05,
       -6.60115446e-05, -6.46502561e-03,  7.57455700e-02,  1.71658272e-01,
       -3.19689024e-01,  9.57033609e-02])

In [160]:
feat_imp = pd.DataFrame({"features":X_train.columns,"importance":logistic_model.coef_[0]}).sort_values("importance", ascending=False)
feat_imp

features  importance
2  NumberOfTime30-59DaysPastDueNotWorse    0.279837
7          NumberRealEstateLoansOrLines    0.171658
9                    NumberOfDependents    0.095703
6               NumberOfTimes90DaysLate    0.075746
3                             DebtRatio   -0.000032
4                         MonthlyIncome   -0.000066
0  RevolvingUtilizationOfUnsecuredLines   -0.005890
5       NumberOfOpenCreditLinesAndLoans   -0.006465
1                                   age   -0.049475
8  NumberOfTime60-89DaysPastDueNotWorse   -0.319689

In [103]:
logistic_prediction = logistic_model.predict(X_test)
print(accuracy_score(y_test, logistic_prediction))

0.9361412117494718


In [123]:
confusion_matrix = confusion_matrix(y_test, logistic_prediction)
print(confusion_matrix)

[[13726    14]
 [  923    10]]


In [147]:
X_train.columns

Index(['RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

In [152]:
X_new_dict = dict(zip(X_train.columns,[3, 45, 7, 25, 600, 2, 1, 2, 1, 2]))
X_new = pd.DataFrame(X_new_dict, index=X_new_dict.keys())

In [153]:
logistic_model.predict(X_new)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

## Decision Tree

In [161]:
from sklearn.tree import DecisionTreeRegressor, plot_tree

dtr_model = DecisionTreeRegressor()
dtr_model.fit(X_train,y_train)

DecisionTreeRegressor()

In [162]:
pd.DataFrame({"features":X_train.columns, "importance":dtr_model.feature_importances_}).sort_values("importance", ascending=False)

features  importance
3                             DebtRatio    0.198057
0  RevolvingUtilizationOfUnsecuredLines    0.187409
4                         MonthlyIncome    0.144681
6               NumberOfTimes90DaysLate    0.128491
1                                   age    0.123266
5       NumberOfOpenCreditLinesAndLoans    0.081523
9                    NumberOfDependents    0.043506
2  NumberOfTime30-59DaysPastDueNotWorse    0.039065
7          NumberRealEstateLoansOrLines    0.027763
8  NumberOfTime60-89DaysPastDueNotWorse    0.026239

In [164]:
dtr_prediction = dtr_model.predict(X_test)
dtr_prediction

array([0., 0., 1., ..., 0., 0., 0.])

In [165]:
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error, r2_score
import numpy as np

print("Coeficiente determinación", r2_score(y_test, dtr_prediction))
print("MAE", mean_absolute_error(y_test, dtr_prediction))
print("MAPE", mean_absolute_percentage_error(y_test, dtr_prediction))
print("MSE", mean_squared_error(y_test, dtr_prediction))
print("RMSE", np.sqrt(mean_squared_error(y_test, dtr_prediction)))

Coeficiente determinación -0.6851557719329995
MAE 0.10049864831095665
MAPE 249570770599655.12
MSE 0.10033919065252125
RMSE 0.31676361952175197
